### ISSUE TITLE
xamlを使わずにUIを記述する方法を教えてください。（Could you tell me the way to create UI without writing xaml?）

### ISSUE THREAD

**Issue by nadsfds** [sotanakamura/winui-python#1]
はじめまして、もしよろしければ少し教えていただけますでしょうか。

今、PythonプログラムでGUIの表示などをイベントハンドラーなどでいろいろ変えたいと思っていますが、そのようなことは可能なのでしょうか？できればxamlを使わずにプログラム作成できればと思っています。
Githubの他のところで以下のやり取りを拝見しましたが、具体的な方法がよくわかりません。

(In English for English speakers)
Hi, I'm interested in your work, and I have a question on usage of the package.
Could you tell the way to implement event handler or simple function to change the displayed elements in the GUI?
If there is any way, I would like to know some example(if possible, I would like to write code without XAML)!
A Image below is previous conversation on similar usuage but I couldn't find any examples on it.

![image](https://github.com/sotanakamura/winui-python/assets/152662451/4f5fa891-9232-4912-802e-56fd1488587a)

リンク（Link）
_Originally posted by @sotanakamura in https://github.com/microsoft/microsoft-ui-xaml/issues/3364#issuecomment-1831634260_

**Comment by sotanakamura** [comment]
I will show an example migrating c# sample code into python code.

Here, I use the sample program of [RepeatButton](https://learn.microsoft.com/en-us/windows/apps/design/controls/buttons).

```xaml
<StackPanel>
    <RepeatButton Width="100" Delay="500" Interval="100" Click="Increase_Click">Increase</RepeatButton>
    <RepeatButton Width="100" Delay="500" Interval="100" Click="Decrease_Click">Decrease</RepeatButton>
    <TextBlock x:Name="clickTextBlock" Text="Number of Clicks:" />
</StackPanel>
```

```csharp
private static int _clicks = 0;
private void Increase_Click(object sender, RoutedEventArgs e)
{
    _clicks += 1;
    clickTextBlock.Text = "Number of Clicks: " + _clicks;
}

private void Decrease_Click(object sender, RoutedEventArgs e)
{
    if(_clicks > 0)
    {
        _clicks -= 1;
        clickTextBlock.Text = "Number of Clicks: " + _clicks;
    }
}
```

You can migrate the sample code as follows:

```python
from win32more.xaml import XamlApplication
from win32more.Windows.Foundation import PropertyValue
from win32more.Microsoft.UI.Xaml import Window
from win32more.Microsoft.UI.Xaml.Controls import StackPanel, TextBlock
from win32more.Microsoft.UI.Xaml.Controls.Primitives import RepeatButton

class App(XamlApplication):
    def OnLaunched(self, args):
        self.clicks = 0

        win = Window()

        stack = StackPanel()

        incbtn = RepeatButton()
        incbtn.Width = 100
        incbtn.Delay = 500
        incbtn.Interval = 100
        incbtn.add_Click(self.Increase_Click)
        incbtn.Content = PropertyValue.CreateString("Increase")

        decbtn = RepeatButton()
        decbtn.Width = 100
        decbtn.Delay = 500
        decbtn.Interval = 100
        decbtn.add_Click(self.Decrease_Click)
        decbtn.Content = PropertyValue.CreateString("Decrease")

        self.textblock = TextBlock()
        self.textblock.Text = "Number of Clicks:"

        stack.Children.Append(incbtn)
        stack.Children.Append(decbtn)
        stack.Children.Append(self.textblock)

        win.Content = stack
        win.Activate()

    def Increase_Click(self, sender, args):
        self.clicks += 1
        self.textblock.Text = "Number of Clicks: " + str(self.clicks)

    def Decrease_Click(self, sender, args):
        if(self.clicks > 0):
            self.clicks -= 1
            self.textblock.Text = "Number of Clicks: " + str(self.clicks)

XamlApplication.Start(App)
```

**Comment by sotanakamura** [comment]
You can find more examples in [the library's repository](https://github.com/ynkdir/py-win32more/tree/main/example).

**Comment by nadsfds** [comment]
Thank you very much for your quick and detailed response!
I'll give it a try!

**Comment by nadsfds** [comment]
Note:
The example code above didn't work with this repository's 「wunui-python/win32more」

Workaround:
1. get latest win32more from original ynkdir's repository
=> https://github.com/ynkdir/py-win32more
2. replace winui-python/win32more with py-win32more/win32more
3. install same version of 「Windows App SDK」as requirement of ynkdir's win32more (currently stable 1.5.0 (1.5.240227000) )
=> https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads

**Comment by sotanakamura** [comment]
Sorry, I forgot to mention that. I updated my repo and added the sample code named as button-click.py.
