### ISSUE TITLE
Add a TitleBar.

### ISSUE THREAD

**Issue by xiaoshuaiyo** [sotanakamura/winui-python#10]
I defined a software icon when using a custom title bar, but it didn't seem to work.
![b9c1620898e079cd1c57744207873bdb](https://github.com/user-attachments/assets/c5c03081-bee5-4e5c-88e0-5ea2fab7917e)
![1188600e28aa32bb7b372395d350a5e7](https://github.com/user-attachments/assets/3e6be8d7-3e42-453b-87fc-1510b4eb9fce)
Also, I'd like to ask you how I use cards in a page built with XAML.

**Comment by mstouk57g** [comment]
![image](https://github.com/user-attachments/assets/195f629e-027d-442a-912f-20f18d73da5d)

There is no doubt that we are allowed to add images in the applications...

Alright. It is strange that the image do not appear in the titlebar with your code.

But ... You must clear that the keyword " x: " does not work in python.

https://github.com/sotanakamura/winui-python/issues/6

**Comment by xiaoshuaiyo** [comment]
> ![image](https://private-user-images.githubusercontent.com/65524880/356807208-195f629e-027d-442a-912f-20f18d73da5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyODg0NzAsIm5iZiI6MTcyMzI4ODE3MCwicGF0aCI6Ii82NTUyNDg4MC8zNTY4MDcyMDgtMTk1ZjYyOWUtMDI3ZC00NDJhLTkxMmYtMjBmMThkNzNkYTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDExMDkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMzUwZTY3NjgyMWJmMGY1YWY4N2Y1MDEzYmY1MjQ3NTg1MjJlMjc3OGMyMjhmZDQwZGNhNTliMjRjOWYwMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sbg9l7BC0q53lomQj_RUIdXcQoZE8rHND4rLpIWNk3o)
> 
> 毫无疑问，我们可以在应用程序中添加图像...
> 
> 好吧。奇怪的是，图像没有出现在标题栏中。

如果这是在 csharp 中我们需要将图片在解决方案里属性改成内容，但是这是 Python。还有，我用 border 制作了一个卡片，但是我不知道如何将它变为我上个 issue 中那个图片上那样

**Comment by mstouk57g** [comment]
![image](https://github.com/user-attachments/assets/0fa61d33-2a26-4ec5-8e37-a14b8807266b)
我知道你在说什么。但，好像“内容”就是默认模式啊。
同时，我测试了。一个普通的图片，如果使用了自定义标题栏（customtitlebar）的话是可以正常显示的，就像这样
![image](https://github.com/user-attachments/assets/0c0586fb-4f03-4f9c-a7b7-9d4dd2cc2bb8)

**Comment by mstouk57g** [comment]
不过，我也有些好奇。你是如何把这个标题栏的高度做到那么高的？我这里的标题栏的高度。。。和Win默认标题栏一样（
哦，忘记贴上代码了
``` C#
<Page xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="32"/>
            <RowDefinition/>
        </Grid.RowDefinitions>

        <StackPanel Orientation="Horizontal" Name="AppTitleBar" Margin="0,0,10,0">
            <Image Source="D:\KissL\Documents\FormatFactory\FFOutput\WindowIcon.png" Margin="15,8,15,5"/>
            <TextBlock Name="AppTitleTextBlock" Text="App title123"
                       TextWrapping="NoWrap"
                       Style="{StaticResource CaptionTextBlockStyle}"
                       VerticalAlignment="Center"
                       Margin="0,0,0,0"/>
        </StackPanel>

        <Image Source="D:/KissL/Desktop/winui-python/img.jpg" Grid.Row="1"/>
    </Grid>
</Page>
```

**Comment by xiaoshuaiyo** [comment]
> 不过，我也有些好奇。你是如何把这个标题栏的高度做到那么高的？我这里的标题栏的高度。。。和Win默认标题栏一样（ 哦，忘记贴上代码了
> 
> ```cs
> <Page xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">
>     <Grid>
>         <Grid.RowDefinitions>
>             <RowDefinition Height="32"/>
>             <RowDefinition/>
>         </Grid.RowDefinitions>
> 
>         <StackPanel Orientation="Horizontal" Name="AppTitleBar" Margin="0,0,10,0">
>             <Image Source="D:\KissL\Documents\FormatFactory\FFOutput\WindowIcon.png" Margin="15,8,15,5"/>
>             <TextBlock Name="AppTitleTextBlock" Text="App title123"
>                        TextWrapping="NoWrap"
>                        Style="{StaticResource CaptionTextBlockStyle}"
>                        VerticalAlignment="Center"
>                        Margin="0,0,0,0"/>
>         </StackPanel>
> 
>         <Image Source="D:/KissL/Desktop/winui-python/img.jpg" Grid.Row="1"/>
>     </Grid>
> </Page>
> ```

我调整了Height

**Comment by xiaoshuaiyo** [comment]
> 不过，我也有些好奇。你是如何把这个标题栏的高度做到那么高的？我这里的标题栏的高度。。。和Win默认标题栏一样（ 哦，忘记贴上代码了
> 
> ```cs
> <Page xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">
>     <Grid>
>         <Grid.RowDefinitions>
>             <RowDefinition Height="32"/>
>             <RowDefinition/>
>         </Grid.RowDefinitions>
> 
>         <StackPanel Orientation="Horizontal" Name="AppTitleBar" Margin="0,0,10,0">
>             <Image Source="D:\KissL\Documents\FormatFactory\FFOutput\WindowIcon.png" Margin="15,8,15,5"/>
>             <TextBlock Name="AppTitleTextBlock" Text="App title123"
>                        TextWrapping="NoWrap"
>                        Style="{StaticResource CaptionTextBlockStyle}"
>                        VerticalAlignment="Center"
>                        Margin="0,0,0,0"/>
>         </StackPanel>
> 
>         <Image Source="D:/KissL/Desktop/winui-python/img.jpg" Grid.Row="1"/>
>     </Grid>
> </Page>
> ```

`<Grid.RowDefinitions>
            <RowDefinition Height="48" />
            <RowDefinition />
        </Grid.RowDefinitions>
`

**Comment by xiaoshuaiyo** [comment]
> 不过，我也有些好奇。你是如何把这个标题栏的高度做到那么高的？我这里的标题栏的高度。。。和Win默认标题栏一样（ 哦，忘记贴上代码了
> 
> ```cs
> <Page xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">
>     <Grid>
>         <Grid.RowDefinitions>
>             <RowDefinition Height="32"/>
>             <RowDefinition/>
>         </Grid.RowDefinitions>
> 
>         <StackPanel Orientation="Horizontal" Name="AppTitleBar" Margin="0,0,10,0">
>             <Image Source="D:\KissL\Documents\FormatFactory\FFOutput\WindowIcon.png" Margin="15,8,15,5"/>
>             <TextBlock Name="AppTitleTextBlock" Text="App title123"
>                        TextWrapping="NoWrap"
>                        Style="{StaticResource CaptionTextBlockStyle}"
>                        VerticalAlignment="Center"
>                        Margin="0,0,0,0"/>
>         </StackPanel>
> 
>         <Image Source="D:/KissL/Desktop/winui-python/img.jpg" Grid.Row="1"/>
>     </Grid>
> </Page>
> ```

对了我想使用相对路径打开

**Comment by sotanakamura** [comment]
You must use an absolute path because your application is not packaged.
See [Setting Source in XAML](https://learn.microsoft.com/uwp/api/windows.ui.xaml.controls.image.source?view=winrt-26100#setting-source-in-xaml).

**Comment by sotanakamura** [comment]
The way to create cards in XAML is the same as a way in XAML with C#. But, binding items in XAML is not supported. You must append the items to a list in your code.

**Comment by mstouk57g** [comment]
> > 不过，我也有些好奇。你是如何把这个标题栏的高度做到那么高的？我这里的标题栏的高度。。。和Win默认标题栏一样（ 哦，忘记贴上代码了
> > ```cs
> > <Page xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">
> >     <Grid>
> >         <Grid.RowDefinitions>
> >             <RowDefinition Height="32"/>
> >             <RowDefinition/>
> >         </Grid.RowDefinitions>
> > 
> >         <StackPanel Orientation="Horizontal" Name="AppTitleBar" Margin="0,0,10,0">
> >             <Image Source="D:\KissL\Documents\FormatFactory\FFOutput\WindowIcon.png" Margin="15,8,15,5"/>
> >             <TextBlock Name="AppTitleTextBlock" Text="App title123"
> >                        TextWrapping="NoWrap"
> >                        Style="{StaticResource CaptionTextBlockStyle}"
> >                        VerticalAlignment="Center"
> >                        Margin="0,0,0,0"/>
> >         </StackPanel>
> > 
> >         <Image Source="D:/KissL/Desktop/winui-python/img.jpg" Grid.Row="1"/>
> >     </Grid>
> > </Page>
> > ```
> 
> `<Grid.RowDefinitions> <RowDefinition Height="48" /> <RowDefinition /> </Grid.RowDefinitions> `

啊！（忘了这个了，不是经常用）（我总是喜欢用stackpanel解决问题）

**Comment by mstouk57g** [comment]
> > > 不过，我也有些好奇。你是如何把这个标题栏的高度做到那么高的？我这里的标题栏的高度。。。和Win默认标题栏一样（ 哦，忘记贴上代码了
> > > ```cs
> > > <Page xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">
> > >     <Grid>
> > >         <Grid.RowDefinitions>
> > >             <RowDefinition Height="32"/>
> > >             <RowDefinition/>
> > >         </Grid.RowDefinitions>
> > > 
> > >         <StackPanel Orientation="Horizontal" Name="AppTitleBar" Margin="0,0,10,0">
> > >             <Image Source="D:\KissL\Documents\FormatFactory\FFOutput\WindowIcon.png" Margin="15,8,15,5"/>
> > >             <TextBlock Name="AppTitleTextBlock" Text="App title123"
> > >                        TextWrapping="NoWrap"
> > >                        Style="{StaticResource CaptionTextBlockStyle}"
> > >                        VerticalAlignment="Center"
> > >                        Margin="0,0,0,0"/>
> > >         </StackPanel>
> > > 
> > >         <Image Source="D:/KissL/Desktop/winui-python/img.jpg" Grid.Row="1"/>
> > >     </Grid>
> > > </Page>
> > > ```
> > 
> > 
> > `<Grid.RowDefinitions> <RowDefinition Height="48" /> <RowDefinition /> </Grid.RowDefinitions> `
> 
> 啊！（忘了这个了，不是经常用）（我老是喜欢用stackpanel解决问题）

**Comment by S-1-5-21-1726115** [comment]
原来你也是来写Minecraft启动器的（喜）

**Comment by S-1-5-21-1726115** [comment]
> You must use an absolute path because your application is not packaged. See [Setting Source in XAML](https://learn.microsoft.com/uwp/api/windows.ui.xaml.controls.image.source?view=winrt-26100#setting-source-in-xaml).

其实你可以这么写：<Image Source="!~{WorkDir}/Path/To/YourImage.png" ... />
然后在Python侧替换（）
