### ISSUE TITLE
Selector.txt file used to generator win32more folder

### ISSUE THREAD

**Issue by rileymjohnson** [sotanakamura/winui-python#3]
The win32more folder was presumably generated using the [py-win32more](https://github.com/ynkdir/py-win32more/tree/main) tool, which uses a `selector.txt` file to determine what to include in it. What is the `selector.txt` file that was used? I can't seem to generate the following folders / files:

- `mddbootstrap`
- `__init__.py`
- `_winrt.py`
- `xaml.py`

**Comment by sotanakamura** [comment]
I think that those files were created by the author manually. win32more includes all windows runtime apis, but you can generate specific apis that you need by using the file. Please ask details for the original author.

**Comment by sotanakamura** [comment]
The Windows folder includes windows runtime apis in Windows namespace and the Microsoft folder includes windows app sdk and winui 3 apis in Microsoft namespace.

**Comment by sotanakamura** [comment]
I think you need to create the selector.txt file by following the readme.
