### ISSUE TITLE
Is it possible to set a custom titlebar as in WIN UI gallery?

### ISSUE THREAD

**Issue by echidne** [sotanakamura/winui-python#6]
Hi,
It's not really an issue but I'm wondering how to set a custom titlebar (to get rid fo the system title bar).
The exemple given by Microsoft is : 
```
// UIElement set as titlebar
<Border x:Name="AppTitleBar" Grid.Column="1" VerticalAlignment="Top">
    <TextBlock x:Name="AppTitle" Text="{StaticResource AppTitleName}" VerticalAlignment="Top" Margin="0,8,0,0" />
</Border>

// C# code to set AppTitleBar uielement as titlebar
Window window = App.MainWindow;
window.ExtendsContentIntoTitleBar = true;  // enable custom titlebar
window.SetTitleBar(AppTitleBar);      // set user ui element as titlebar
```
I try to add the Border definition in the xaml but when i do that that raise the following error when I try to read it with XamlReader as in your example: 
File "c:\Users\Philippe\Documents\Codes_Python\WinUI-python\winui-python-main\win32more\_winrt.py", line 239, in __call__
    raise WinError(hr)
OSError: [WinError -2144665590]
I confess I'm not an expert in windows desktop programmation nor in XAML . 
Can you help me or that is not possible at the stage of development of WinUI-python?

Thank in advance

PS: I'm developping on Windows 10 22H2

**Comment by sotanakamura** [comment]
First of all, I recommend you to learn the basics of XAML with C# before using this Python APIs.

The prefix "x:" currently has been not supported. The "x:Name" tag generates a variable to access its control using the an external tool (XAML compiler). In Python, you need to use `FrameworkElement.FindName(String)` to get a reference to the named control.

```xaml
<Page xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="32"/>
            <RowDefinition/>
        </Grid.RowDefinitions>

        <Grid Name="AppTitleBar">
            <TextBlock Name="AppTitleTextBlock" Text="App title"
                       TextWrapping="NoWrap"
                       Style="{StaticResource CaptionTextBlockStyle}" 
                       VerticalAlignment="Center"
                       Margin="28,0,0,0"/>
        </Grid>

        <NavigationView Grid.Row="1">
            <!-- Page content -->
        </NavigationView>
    </Grid>
</Page>
```

```py
from win32more.xaml import XamlApplication
from win32more.Microsoft.UI.Xaml import Window
from win32more.Microsoft.UI.Xaml.Media import MicaBackdrop
from win32more.Microsoft.UI.Xaml.Markup import XamlReader
from win32more.Microsoft.UI.Xaml.Controls import Page

class App(XamlApplication):
    def OnLaunched(self, args):
        win = Window()
        win.SystemBackdrop = MicaBackdrop()
        with open("page.xaml", "r", encoding='utf-8') as file:
            win.Content = XamlReader.Load(file.read())
        win.ExtendsContentIntoTitleBar = True
        win.SetTitleBar(win.Content.as_(Page).FindName("AppTitleBar"))
        win.Activate()

XamlApplication.Start(App)

```

**Comment by echidne** [comment]
Thank you very much.
I'll follow your advice and learn a bit of XAML 👍 
In your ReadMe you say that its also possible to do without XAML, but I suppose that could be more tricky.
Have a nice day.

**Comment by S-1-5-21-1726115** [comment]
当然你也可以改用win32more.xaml里面的XamlLoader
这会自动添加x:Name里面的内容字段
