### ISSUE TITLE
I wonder how to navigate pages by using the NavigationView

### ISSUE THREAD

**Issue by mstouk57g** [sotanakamura/winui-python#7]
Pages are created by XAML .
I can use C# to navigate , but I down’t know how to do it with Python.

**Comment by sotanakamura** [comment]
Frame.Navigate is not supported because it requires the implementation of a Windows Runtime class which is not supported in python language projection. We need to set the content of a NavigationView. We can not use the back button of a NavigationView.

Here is the sample code of navigation (I tried to set ContentTransitions to animate the transitions, but it did not work):

navigation.xaml
```xaml
<NavigationView xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" IsBackButtonVisible="Collapsed" Name="NavigationView">
    <NavigationView.ContentTransitions>
        <TransitionCollection>
            <EntranceThemeTransition/>
        </TransitionCollection>
    </NavigationView.ContentTransitions>
    <NavigationView.MenuItems>
        <NavigationViewItem Content="Page 1" Tag="page1"/>
        <NavigationViewItem Content="Page 2" Tag="page2"/>
    </NavigationView.MenuItems>
</NavigationView>
```

page1.xaml
```xaml
<Page xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">
    <TextBlock Text="Page 1" FontSize="40" Padding="10" HorizontalAlignment="Center" VerticalAlignment="Center"/>
</Page>
```

page2.xaml
```xaml
<Page xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">
    <TextBlock Text="Page 2" FontSize="40" Padding="10" HorizontalAlignment="Center" VerticalAlignment="Center"/>
</Page>
```

winui-xaml.py
```py
from win32more.xaml import XamlApplication
from win32more._winrt import unbox_value
from win32more.Windows.Foundation import IStringable
from win32more.Microsoft.UI.Xaml import Window
from win32more.Microsoft.UI.Xaml.Controls import NavigationView, NavigationViewItem
from win32more.Microsoft.UI.Xaml.Media import MicaBackdrop
from win32more.Microsoft.UI.Xaml.Markup import XamlReader
from win32more.Microsoft.UI.Xaml.Media.Animation import EntranceThemeTransition

class App(XamlApplication):
    def OnLaunched(self, args):
        win = Window()
        win.SystemBackdrop = MicaBackdrop()
        with open("navigation.xaml", "r", encoding='utf-8') as file:
            win.Content = XamlReader.Load(file.read())
            win.Content.as_(NavigationView).add_ItemInvoked(self.ItemInvoked)
        win.Activate()

    def ItemInvoked(self, sender, args):
        nav = sender.as_(NavigationView)
        navitem = args.InvokedItemContainer.as_(NavigationViewItem)
        filename = unbox_value(navitem.Tag)
        with open(filename + ".xaml", "r", encoding='utf-8') as file:
            nav.Content = XamlReader.Load(file.read())
        
XamlApplication.Start(App)
```

**Comment by mstouk57g** [comment]
Oh! It works!
Thanks you a lot~

**Comment by mstouk57g** [comment]
Maybe you can put all the codes which is in issues into the repositorie.
So that everyone can know how to do these easily, without finding in issues.
Include #6

**Comment by mstouk57g** [comment]
(And by the way, I have found that you have already deleted ``requirements.txt`` which I added.
But the command to install modules is depend on it.
Maybe you should change the ReadME.md to ``pip install win32more`` or the command will raise an error.)

**Comment by S-1-5-21-1726115** [comment]
啊...其实你可以这样：from typing_extensions import override
from win32more.Microsoft.UI.Xaml import Controls,Window,Thickness
from win32more.Microsoft.UI.Windowing import TitleBarHeightOption
from win32more.Microsoft.UI.Xaml.Media import MicaBackdrop
from win32more.xaml import XamlApplication,XamlLoader,XamlType,xaml_typename
from win32more.Windows.UI.Xaml.Interop import TypeKind
from win32more.Windows.Win32.System.WinRT import IInspectable
from win32more._winrt import ComPtr
from traceback import format_exception
from Account import AccountManager #喵的这Shit山把我自己都给看懵了

def LoadXaml(NameSpace:object,Xaml:str)->ComPtr:
    try:
        return XamlLoader.Load(NameSpace,Xaml)
    except Exception as E:
        raise SyntaxError("\nEN-US: Can't load '{0}'.Please check this file.\n中文:无法加载'{0}',请检查此文件是否存在语法/其他错误。\nException:\n{1}".format(Xaml,"".join(format_exception(E))))

class App(XamlApplication):
    @override #重写这个函数
    def OnLaunched(self,args):
        self.IsUpdateNavigationView=False
        self.Window=Window()
        self.Window.Title="Test"
        self.Window.SystemBackdrop=MicaBackdrop()
        self.Layout=LoadXaml(self,open("MainWindow.xaml",encoding="UTF-16-LE").read())
        #上面这个东西在载入的同时也会绑定命名空间（但Pylance不认），所以看到无法注解的并不奇怪
        self.Frame:Controls.Frame #但还是注解一下为好()
        self.NavigationView:Controls.NavigationView
        self.AppTitleBar:Controls.Grid
        self.AppTitleText:Controls.TextBlock
        self.PageStack:list[tuple[str,Controls.NavigationViewItem]]=[]
        self.NavigationView.SelectedItem=self.NavigationView.MenuItems[0] #首页
        self.Window.Content=self.Layout
        self.Window.ExtendsContentIntoTitleBar=True
        self.Window.SetTitleBar(self.AppTitleBar)
        self.Window.AppWindow.TitleBar.PreferredHeightOption=TitleBarHeightOption.Tall
        self.Window.Activate()
    
    def SelectedItemChanged(self,sender,args):
        SelectedItem=args.SelectedItem.as_(Controls.NavigationViewItem)
        sender.Header=SelectedItem.Content
        if not self.IsUpdateNavigationView:
            Tag=SelectedItem.Tag.as_(str)
            self.Frame.Navigate(xaml_typename(Tag,TypeKind.Custom))
            self.NavigationView.IsBackEnabled=self.Frame.CanGoBack
            self.PageStack.append((Tag,SelectedItem))
        else:
            self.IsUpdateNavigationView=False
    
    def DisplayModeChanged(self,sender,args):
        DisplayMode=args.DisplayMode
        if DisplayMode==Controls.NavigationViewDisplayMode.Minimal:
            self.AppTitleBar.Margin=Thickness(96,0,0,0)
            sender.PaneTitle="" #防止错位
        else:
            self.AppTitleBar.Margin=Thickness(48,0,0,0)
            sender.PaneTitle="Test"
    
    def BackRequested(self,sender,args):
        self.IsUpdateNavigationView=True
        if self.Frame.CanGoBack:
            self.Frame.GoBack()
            if self.PageStack:
                self.PageStack.pop()
                if self.PageStack:
                    Tag,SelectedItem=self.PageStack[-1]
                    self.NavigationView.SelectedItem=SelectedItem
                    args.Handled=True
            if not self.Frame.CanGoBack:
                self.NavigationView.IsBackEnabled=False
                args.Handled=False

    @override
    def GetXamlTypeByFullName(self,typename):
        print(typename)
        if typename=="App.Home":
            return XamlType("App.Home",TypeKind.Custom,activate_instance=Home)
        elif typename=="Settings":
            return XamlType("Settings",TypeKind.Custom,activate_instance=Settings)
        elif typename=="Launcher.CommunityResource":
            return XamlType("Launcher.CommunityResource",TypeKind.Custom,activate_instance=CommunityResource)
        return super().GetXamlTypeByFullName(typename)
    
    @classmethod
    def run(cls):
        XamlApplication.Start(cls)

def Home():
    class HomePageNamespace:
        #目前Xaml里面还没有类型绑定
        pass
    return LoadXaml(HomePageNamespace(),open("TestPage.xaml","r",encoding="UTF-16-LE").read())

def Settings():
    class SettingsPageNamespace:
        #同理
        pass
    return LoadXaml(SettingsPageNamespace(),open("Setting.xaml","r",encoding="UTF-16-LE").read())

def CommunityResource():
    class CommunityResourcePageNamespace:
        def NavigateToModDownloadPage(self,sender,args):
            pass
    return LoadXaml(CommunityResourcePageNamespace(),open("CommunityResource.xaml","r",encoding="UTF-16-LE").read())

App.run()

**Comment by S-1-5-21-1726115** [comment]
啊...其实你可以这样:
```python
from typing_extensions import override
from win32more.Microsoft.UI.Xaml import Controls,Window,Thickness
from win32more.Microsoft.UI.Windowing import TitleBarHeightOption
from win32more.Microsoft.UI.Xaml.Media import MicaBackdrop
from win32more.xaml import XamlApplication,XamlLoader,XamlType,xaml_typename
from win32more.Windows.UI.Xaml.Interop import TypeKind
from win32more.Windows.Win32.System.WinRT import IInspectable
from win32more._winrt import ComPtr
from traceback import format_exception

def LoadXaml(NameSpace:object,Xaml:str)->ComPtr:
    try:
        return XamlLoader.Load(NameSpace,Xaml)
    except Exception as E:
        raise SyntaxError("\nEN-US: Can't load '{0}'.Please check this file.\n中文:无法加载'{0}',请检查此文件是否存在语法/其他错误。\nException:\n{1}".format(Xaml,"".join(format_exception(E))))

class App(XamlApplication):
    @override #重写这个函数
    def OnLaunched(self,args):
        self.IsUpdateNavigationView=False
        self.Window=Window()
        self.Window.Title="Test"
        self.Window.SystemBackdrop=MicaBackdrop()
        self.Layout=LoadXaml(self,open("MainWindow.xaml",encoding="UTF-16-LE").read())
        #上面这个东西在载入的同时也会绑定命名空间（但Pylance不认），所以看到无法注解的并不奇怪
        self.Frame:Controls.Frame #但还是注解一下为好()
        self.NavigationView:Controls.NavigationView
        self.AppTitleBar:Controls.Grid
        self.AppTitleText:Controls.TextBlock
        self.PageStack:list[tuple[str,Controls.NavigationViewItem]]=[]
        self.NavigationView.SelectedItem=self.NavigationView.MenuItems[0] #首页
        self.Window.Content=self.Layout
        self.Window.ExtendsContentIntoTitleBar=True
        self.Window.SetTitleBar(self.AppTitleBar)
        self.Window.AppWindow.TitleBar.PreferredHeightOption=TitleBarHeightOption.Tall
        self.Window.Activate()
    
    def SelectedItemChanged(self,sender,args):
        SelectedItem=args.SelectedItem.as_(Controls.NavigationViewItem)
        sender.Header=SelectedItem.Content
        if not self.IsUpdateNavigationView:
            Tag=SelectedItem.Tag.as_(str)
            self.Frame.Navigate(xaml_typename(Tag,TypeKind.Custom))
            self.NavigationView.IsBackEnabled=self.Frame.CanGoBack
            self.PageStack.append((Tag,SelectedItem))
        else:
            self.IsUpdateNavigationView=False
    
    def DisplayModeChanged(self,sender,args):
        DisplayMode=args.DisplayMode
        if DisplayMode==Controls.NavigationViewDisplayMode.Minimal:
            self.AppTitleBar.Margin=Thickness(96,0,0,0)
            sender.PaneTitle="" #防止错位
        else:
            self.AppTitleBar.Margin=Thickness(48,0,0,0)
            sender.PaneTitle="Test"
    
    def BackRequested(self,sender,args):
        self.IsUpdateNavigationView=True
        if self.Frame.CanGoBack:
            self.Frame.GoBack()
            if self.PageStack:
                self.PageStack.pop()
                if self.PageStack:
                    Tag,SelectedItem=self.PageStack[-1]
                    self.NavigationView.SelectedItem=SelectedItem
                    args.Handled=True
            if not self.Frame.CanGoBack:
                self.NavigationView.IsBackEnabled=False
                args.Handled=False

    @override
    def GetXamlTypeByFullName(self,typename):
        print(typename)
        if typename=="App.Home":
            return XamlType("App.Home",TypeKind.Custom,activate_instance=Home)
        elif typename=="Settings":
            return XamlType("Settings",TypeKind.Custom,activate_instance=Settings)
        elif typename=="Launcher.CommunityResource":
            return XamlType("Launcher.CommunityResource",TypeKind.Custom,activate_instance=CommunityResource)
        return super().GetXamlTypeByFullName(typename)
    
    @classmethod
    def run(cls):
        XamlApplication.Start(cls)

def Home():
    class HomePageNamespace:
        #目前Xaml里面还没有类型绑定
        pass
    return LoadXaml(HomePageNamespace(),open("TestPage.xaml","r",encoding="UTF-16-LE").read())

def Settings():
    class SettingsPageNamespace:
        #同理
        pass
    return LoadXaml(SettingsPageNamespace(),open("Setting.xaml","r",encoding="UTF-16-LE").read())

def CommunityResource():
    class CommunityResourcePageNamespace:
        def NavigateToModDownloadPage(self,sender,args):
            pass
    return LoadXaml(CommunityResourcePageNamespace(),open("CommunityResource.xaml","r",encoding="UTF-16-LE").read())

App.run()
```

**Comment by S-1-5-21-1726115** [comment]
基于[win32more里面的示例](https://raw.githubusercontent.com/ynkdir/py-win32more/refs/heads/main/example/winui-navigationview.py)
