### ISSUE TITLE
I want to make a card.

### ISSUE THREAD

**Issue by xiaoshuaiyo** [sotanakamura/winui-python#9]
Do you know how to make a card similar to this in WinUI3 for Python?
![3b88a50e2a5a602ce96f4d757a22cb2d](https://github.com/user-attachments/assets/b1feb584-0d87-4588-b0c5-a15a0375ea0e)
I also want it to do the following：
1.Cards are automatically added based on a list when a refresh button is clicked
2.The cards are all in a scrolling area and use a fluid layout
3.When you click a button in a card, it automatically gets the text of the Textblock in the card where the button is located

4.Cards have a fixed template, and the content of the template is automatically modified when the card is added

I love WinUI3 so much that I didn't expect to be able to use it in Python one day

**Comment by sotanakamura** [comment]
Sorry, I have no time to implement the all features. This is the minimal sample code showing the cards.

```python
from win32more._winrt import unbox_value
from win32more.xaml import XamlApplication
from win32more.Microsoft.UI.Xaml import Window
from win32more.Microsoft.UI.Xaml.Controls import GridView, Border, TextBlock
from win32more.Microsoft.UI.Xaml.Media import SolidColorBrush
from win32more.Windows.UI import Colors
from win32more.Windows.Foundation import PropertyValue

class App(XamlApplication):
    def OnLaunched(self, args):
        win = Window()
        grid = GridView()
        grid.IsItemClickEnabled = True
        grid.add_ItemClick(self.ItemClicked)
        for i in range(10):
            border = Border()
            border.Background = SolidColorBrush(Colors.DarkGray)
            border.Width = 200
            border.Height = 150
            name = "Card" + str(i)
            border.Tag = PropertyValue.CreateString(name)
            text = TextBlock()
            text.Text = name
            border.Child = text
            grid.Items.Append(border)
        win.Content = grid
        win.Activate()

    def ItemClicked(self, sender, args):
        border = args.ClickedItem.as_(Border)
        tag = border.Tag
        textblock = border.Child.as_(TextBlock)
       textblock.Text = textblock.Text.split(' ', 1)[0] + " was clicked!"
        

XamlApplication.Start(App)
```

**Comment by xiaoshuaiyo** [comment]
> Sorry, I have no time to implement the all features. This is the minimal sample code showing the cards.
> 
> ```python
> from win32more._winrt import unbox_value
> from win32more.xaml import XamlApplication
> from win32more.Microsoft.UI.Xaml import Window
> from win32more.Microsoft.UI.Xaml.Controls import GridView, Border, TextBlock
> from win32more.Microsoft.UI.Xaml.Media import SolidColorBrush
> from win32more.Windows.UI import Colors
> from win32more.Windows.Foundation import PropertyValue
> 
> class App(XamlApplication):
>     def OnLaunched(self, args):
>         win = Window()
>         grid = GridView()
>         grid.IsItemClickEnabled = True
>         grid.add_ItemClick(self.ItemClicked)
>         for i in range(10):
>             border = Border()
>             border.Background = SolidColorBrush(Colors.DarkGray)
>             border.Width = 200
>             border.Height = 150
>             name = "Card" + str(i)
>             border.Tag = PropertyValue.CreateString(name)
>             text = TextBlock()
>             text.Text = name
>             border.Child = text
>             grid.Items.Append(border)
>         win.Content = grid
>         win.Activate()
> 
>     def ItemClicked(self, sender, args):
>         border = args.ClickedItem.as_(Border)
>         tag = border.Tag
>         textblock = border.Child.as_(TextBlock)
>        textblock.Text = textblock.Text.split(' ', 1)[0] + " was clicked!"
>         
> 
> XamlApplication.Start(App)
> ```

I want to create a page and GridView using xaml and use this method, and the background of the card you made looks different than I wanted.

**Comment by mstouk57g** [comment]
Maybe this issue could help you.
https://github.com/microsoft/microsoft-ui-xaml/issues/6543
![image](https://github.com/user-attachments/assets/eff19c0a-4293-4adb-8e52-c779ed8e5356)
